const staffData = [

  {staff: 'Joe', total: 100, rosteredTotal: 43, categories: {cat1: {name: 'Normal', standard: 1, rostered: 1}, cat2: {name: 'Saturday', standard: 5, rostered: 50}, cat3: {name: 'Sunday', standard: 89, rostered: 50}, cat4: {name: 'Night', standard: 1, rostered: 50}, cat5: {name: 'Public Hols', standard: 22, rostered: 90}, cat6: {name: 'Wayne Normal', standard: 55, rostered: 40}, cat7: {name: 'Wayne Saturday', standard: 72, rostered: 220}, cat8: {name: 'Wayne Sunday', standard: 21, rostered: 30}, cat9: {name: 'Wayne Night', standard: 43, rostered: 11}, cat10: {name: 'Wayne Pub Hols', standard: 43, rostered: 20}, cat11: {name: 'Annual Leave', standard: 34, rostered: 123}, cat12: {name: 'Sick Leave', standard: 33, rostered: 120}, cat13: {name: 'Long Service Leave', standard: 66, rostered: 50}, cat14: {name: 'Sleep Overs', standard: 2, rostered: 44}}},

  {staff: 'Steve', total: 100, rosteredTotal: 43, categories: {cat1: {name: 'Normal', standard: 2, rostered: 2}, cat2: {name: 'Saturday', standard: 5, rostered: 50}, cat3: {name: 'Sunday', standard: 89, rostered: 50}, cat4: {name: 'Night', standard: 1, rostered: 50}, cat5: {name: 'Public Hols', standard: 22, rostered: 90}, cat6: {name: 'Wayne Normal', standard: 55, rostered: 40}, cat7: {name: 'Wayne Saturday', standard: 72, rostered: 220}, cat8: {name: 'Wayne Sunday', standard: 21, rostered: 30}, cat9: {name: 'Wayne Night', standard: 43, rostered: 11}, cat10: {name: 'Wayne Pub Hols', standard: 43, rostered: 20}, cat11: {name: 'Annual Leave', standard: 34, rostered: 123}, cat12: {name: 'Sick Leave', standard: 33, rostered: 120}, cat13: {name: 'Long Service Leave', standard: 66, rostered: 50}, cat14: {name: 'Sleep Overs', standard: 2, rostered: 44}}},

  {staff: 'Jack', total: 100, rosteredTotal: 43, categories: {cat1: {name: 'Normal', standard: 3, rostered: 3}, cat2: {name: 'Saturday', standard: 5, rostered: 50}, cat3: {name: 'Sunday', standard: 89, rostered: 50}, cat4: {name: 'Night', standard: 1, rostered: 50}, cat5: {name: 'Public Hols', standard: 22, rostered: 90}, cat6: {name: 'Wayne Normal', standard: 55, rostered: 40}, cat7: {name: 'Wayne Saturday', standard: 72, rostered: 220}, cat8: {name: 'Wayne Sunday', standard: 21, rostered: 30}, cat9: {name: 'Wayne Night', standard: 43, rostered: 11}, cat10: {name: 'Wayne Pub Hols', standard: 43, rostered: 20}, cat11: {name: 'Annual Leave', standard: 34, rostered: 123}, cat12: {name: 'Sick Leave', standard: 33, rostered: 120}, cat13: {name: 'Long Service Leave', standard: 66, rostered: 50}, cat14: {name: 'Sleep Overs', standard: 2, rostered: 44}}},
]

module.exports = staffData
